src/OC/PlatformBundle/Entity/Image.php
<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Image
 *
 * @ORM\Table(name="oc_image")
 * @ORM\Entity(repositoryClass="OC\PlatformBundle\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    private $file;

    //Stock le nom du fichier temporaire
    private $tempFilename;
    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url.
     *
     * @param string $url
     *
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url.
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt.
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt.
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }

	public function getFile()
	{
		return $this->file;
	}

	//Se charge de la sauvegarde du fichier
	public function setFile(UploadedFile $file = null)
	{
		$this->file = $file;

		// On vérifie si on avait déjà un fichier pour cette entité
		if (null !== $this->url) {
			// On sauvegarde l'extension du fichier pour le supprimer plus tard
			$this->tempFilename = $this->url;
			// On réinitialise les valeurs des attributs url et alt
			$this->url = null;
			$this->alt = null;
		}
	}

	/**
	 * @ORM\PrePersist()
	 * @ORM\PreUpdate()
	 */
	public function preUpload()
	{
		if (null === $this->file) {
			return;
		}

		$this->url = $this->file->guessExtension();

		$this->alt = $this->file->getClientOriginalName();
	}

	/**
	 * @ORM\PostPersist()
	 * @ORM\PostUpdate()
	 */
	public function upload()
	{
		if (null === $this->file) {
			return;
		}

		if (null !== $this->tempFilename) {
			$oldFIle = $this->getUploadRootDir() . '/' . $this->id . '.' . $this->tempFilename;
			if (file_exists($oldFIle)) {
				unlink($oldFIle);
			}
		}

		$this->file->move(
			$this->getUploadRootDir(),
			$this->id . '.' . $this->url
		);
	}

	/**
	 * @ORM\PreRemove()
	 */
	public function preRemoveUpload()
	{
		$this->tempFilename = $this->getUploadRootDir() . '/' . $this->id . '.' . $this->url;
	}

	/**
	 * @ORM\PostRemove()
	 */
	public function removeUpload()
	{
		if (file_exists($this->tempFilename)) {
			unlink($this->tempFilename);
		}
	}

	/**
	 * @return string
	 */
	public function getUploadDir()
	{
		// On retourne le chemin relatif vers l'image pour un navigateur (relatif au répertoire /web donc)
		return 'uploads/img';
	}

	/**
	 * @return string
	 */
	protected function getUploadRootDir()
	{
		// On retourne le chemin relatif vers l'image pour notre code PHP
		return __DIR__.'/../../../../web/'.$this->getUploadDir();
	}

	/**
	 * @return string
	 */
	public function getWebPath()
	{
		return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
	}
}

src/OC/PlatformBundle/Form/AdvertType.php
<?php

namespace OC\PlatformBundle\Form;

use OC\PlatformBundle\Repository\CategoryRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;


class AdvertType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
    	$pattern = 'D%';

	    $builder
		    ->add('date',      DateTimeType::class)
		    ->add('title',     TextType::class)
		    ->add('email',     EmailType::class)
		    ->add('author',    TextType::class)
		    ->add('content',   TextareaType::class)
		    ->add('image',     ImageType::class)
		    ->add('categories', EntityType::class, array(
		    	'class' => 'OCPlatformBundle:Category',
			    'choice_label' => 'name',
			    'multiple' => true,
			    'query_builder' => function(CategoryRepository $repository) use ($pattern) {
		    		return $repository->getLikeQueryBuilder($pattern);
			    }
		    ))
		    ->add('save',      SubmitType::class)
	    ;

	    $builder->addEventListener(
	    	FormEvents::PRE_SET_DATA,
		    function (FormEvent $event) {
	    		$advert = $event->getData();

	    		if(null === $advert) {
	    			return;
			    }

	    		if(!$advert->getPublished() || null === $advert->getId() ) {
	    			$event->getForm()->add('published', CheckboxType::class, array('required' => false));

			    } else {
	    			$event->getForm()->remove('published');
			    }
		    }
	    );
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'OC\PlatformBundle\Entity\Advert'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'oc_platformbundle_advert';
    }


}

src/OC/PlatformBundle/Controller/AdvertController.php
<?php
/**
 * Created by PhpStorm.
 * User: j.certain
 * Date: 24/01/2019
 * Time: 12:45
 */

namespace OC\PlatformBundle\Controller;

use OC\PlatformBundle\Entity\Advert;
use OC\PlatformBundle\Entity\AdvertSkill;
use OC\PlatformBundle\Entity\Application;
use OC\PlatformBundle\Entity\Image;
use OC\PlatformBundle\Form\AdvertEditType;
use OC\PlatformBundle\Form\AdvertType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class AdvertController extends Controller
{

	/**
	 * @param $page
	 * @return \Symfony\Component\HttpFoundation\Response
	 * @throws \Exception
	 */
	public function indexAction($page)
	{
		if ($page < 1) {
			throw new NotFoundHttpException('Page "'.$page.'" does not exist.');
		}

		$repository = $this->getDoctrine()->getManager()->getRepository('OCPlatformBundle:Advert');
		$nbPerPage = 2;
		$listAdverts = $repository->getAdverts($page, $nbPerPage);

		$nbPages = ceil(count($listAdverts) / $nbPerPage);

		if($page > $nbPages) {
			throw $this->createNotFoundException('The page '. $page . ' does not exist');
		}

		return $this->render('OCPlatformBundle:Advert:index.html.twig', array(
			'listAdverts' => $listAdverts,
			'nbPages' => $nbPages,
			'page' => $page,
		));
	}

	/**
	 * @param $id
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function viewAction($id)
	{
		$em = $this->getDoctrine()->getManager();

		$advert = $em->getRepository('OCPlatformBundle:Advert')->find($id);

		if (null === $advert) {
			throw new NotFoundHttpException("Announce with " . $id . "doen't exist.");
		}

		$listApplications = $em
			->getRepository('OCPlatformBundle:Application')->findBy(array('advert' => $advert));

		$listAdvertSkills = $em->getRepository('OCPlatformBundle:AdvertSkill')->findBy(array('advert' => $advert));
		return $this->render('OCPlatformBundle:Advert:view.html.twig', array(
			'advert'           => $advert,
			'listApplications' => $listApplications,
			'listAdvertSkills' => $listAdvertSkills
		));
	}

	/**
	 * @Security("has_role('ROLE_USER')")
	 * @param Request $request
	 * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
	 * @throws \Exception
	 */
	public function addAction(Request $request)
	{
		/*if (!$this->get('security.authorization_checker')->isGranted('ROLE_AUTHOR')) {
			throw new AccessDeniedException('Access reserved to Author account.');
		}*/

		//Instancie l'objet pour le Form
		$advert = new Advert();
		$formBuilder = $this->get('form.factory')->create(AdvertType::class, $advert);
		//Raccourcie avec le CTL
		//$form = $this->createForm(AdvertType::class, $advert)

		if($request->isMethod('POST') && $formBuilder->handleRequest($request)->isValid()) {

			$em = $this->getDoctrine()->getManager();
			$em->persist($advert);
			$em->flush();

			$request->getSession()->getFlashBag()->add('notice', 'Advert has been correctly saved.');

		return $this->redirectToRoute('oc_platform_view', array(
			'id' => $advert->getId()
		));
	}

		return $this->render('OCPlatformBundle:Advert:add.html.twig', array(
			'form' => $formBuilder->createView(),
		));
	}

	/**
	 * @param $id
	 * @param Request $request
	 * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
	 */
	public function editAction($id, Request $request)
	{
		$advert = $this->getDoctrine()->getManager()->getRepository('OCPlatformBundle:Advert')->find($id);

		$formBuilder = $this->get('form.factory')->create(AdvertEditType::class, $advert);

		if (null === $advert) {
			throw new NotFoundHttpException("Advert with this ".$id." does not exist.");
		}

		if($request->isMethod('POST') && $formBuilder->handleRequest($request)->isValid()) {

			$em = $this->getDoctrine()->getManager();
			$em->flush();

			$request->getSession()->getFlashBag()->add('notice', 'Advert has been edited.');

			return $this->redirectToRoute('oc_platform_view', array(
				'id' => $advert->getId()
			));
		}

		return $this->render('OCPlatformBundle:Advert:edit.html.twig', array(
			'advert' => $advert,
			'form'   => $formBuilder->createView()
		));
	}

	/**
	 * @param $advertId
	 * @return Response
	 */
	public function editImageAction($advertId)
	{
		$em = $this->getDoctrine()->getManager();

		// On récupère l'annonce
		$advert = $em->getRepository('OCPlatformBundle:Advert')->find($advertId);

		// On modifie l'URL de l'image par exemple
		$advert->getImage()->setUrl('test.png');

		$em->flush();

		return new Response('OK');
	}

	/**
	 * @param $id
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function deleteAction($id, Request $request)
	{

		$em = $this->getDoctrine()->getManager();

		// On récupère l'annonce $id
		$advert = $em->getRepository('OCPlatformBundle:Advert')->find($id);

		if (null === $advert) {
			throw new NotFoundHttpException("L'annonce d'id ".$id." does not exist.");
		}

		$form = $this->get('form.factory')->create();
		if ($request->isMethod('POST') && $form->handleRequest($request)->isValid() ) {
			$em->remove($advert);
			$em->flush();

			$request->getSession()->getFlashBag()->add('info', "L'annonce a bien été supprimée.");

			return $this->redirectToRoute('oc_platform_home');
		}

		return $this->render('OCPlatformBundle:Advert:delete.html.twig', array(
			'advert' => $advert,
			'form'   => $form->createView()
		));
	}

	/**
	 * @return \Symfony\Component\HttpFoundation\Response
	 * Sends data to template
	 */
	public function menuAction($limit)
	{
		$repository = $this->getDoctrine()->getManager()->getRepository('OCPlatformBundle:Advert');

		$listAdverts = $repository->findBy(
			array(),
			array('date' => 'desc'),
			$limit,
			0
		);

		return $this->render('OCPlatformBundle:Advert:menu.html.twig', array('listAdverts' => $listAdverts));
	}

	/**
	 * @param $days
	 */
	public function purgeAction($days, Request $request)
	{
		//Call the service
		$purger = $this->container->get('oc_platform.purger.advert');
		$purger->checkAdvertForPurge($days);

		$request->getSession()->getFlashBag()->add('info', 'Adverts have been purged.');

		return $this->redirectToRoute('oc_platform_home');

	}

	public function testAction()
	{
		$advert = new Advert;

		$advert->setDate(new \Datetime());  // Champ « date » OK
		$advert->setTitle('abc');           // Champ « title » incorrect : moins de 10 caractères
		//$advert->setContent('blabla');    // Champ « content » incorrect : on ne le définit pas
		$advert->setAuthor('A');            // Champ « author » incorrect : moins de 2 caractères

		// On récupère le service validator
		$validator = $this->get('validator');

		// On déclenche la validation sur notre object
		$listErrors = $validator->validate($advert);

		// Si $listErrors n'est pas vide, on affiche les erreurs
		if(count($listErrors) > 0) {
			// $listErrors est un objet, sa méthode __toString permet de lister joliement les erreurs
			return new Response((string) $listErrors);
		} else {
			return new Response("L'annonce est valide !");
		}
	}
}

src/OC/PlatformBundle/Resources/views/Advert/add.html.twig
{% extends "OCPlatformBundle::layout.html.twig" %}

{% block body %}
    <a href="{{ path("oc_platform_home") }}">Home</a>

    <h2>Add a new advert</h2>

    {{ include("OCPlatformBundle:Advert:form.html.twig") }}

    <div>
        {% for message in app.session.flashbag.get('info') %}
            <p>Message Flash: {{ message }}</p>
        {% endfor %}
    </div>

    <p>
        Please note that this advert will be directly display on the homepage once it is submitted.
    </p>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/delete.html.twig
{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Delete an advert - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

    <h2>Delete an advert</h2>

    <p>
        Really sure to delete this one "{{ advert.title }}" ?
    </p>

    {# On met l'id de l'annonce dans la route de l'action du formulaire #}
    <form action="{{ path('oc_platform_delete', {'id': advert.id}) }}" method="post">
        <a href="{{ path('oc_platform_view', {'id': advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Back to original advert
        </a>
        {# Ici j'ai écrit le bouton de soumission à la main #}
        <input type="submit" value="Supprimer" class="btn btn-danger" />
        {# Ceci va générer le champ CSRF #}
        {{ form_rest(form) }}
    </form>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/edit.html.twig
{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Edit advert - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

    <h2>Edition</h2>

    {{ include("OCPlatformBundle:Advert:form.html.twig") }}
    <p>
        <a href="{{ path('oc_platform_view', {'id': advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Go back to previous advert
        </a>
    </p>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/form.html.twig
<h3>Advert Form</h3>

<div class="well">
    {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

    {# Les erreurs générales du formulaire. #}
    {{ form_errors(form) }}

    {# Génération du label + error + widget pour un champ. #}
    {% if form.date is defined %}
        {{ form_row(form.date) }}
    {% endif %}

    {# Génération manuelle et éclatée : #}
    <div class="form-group">
        {# Génération du label. #}
        {{ form_label(form.title, "Titre de l'annonce", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

        {# Affichage des erreurs pour ce champ précis. #}
        {{ form_errors(form.title) }}

        <div class="col-sm-10">
            {# Génération de l'input. #}
            {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>

    {# Idem pour un autre champ. #}
    <div class="form-group">
        {{ form_label(form.content, "Contenu de l'annonce", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        {{ form_errors(form.title) }}
        <div class="col-sm-10">
            {{ form_widget(form.content, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>

    {{ form_row(form.author) }}

    {% if form.published is defined %}
        {{ form_row(form.published) }}
    {% endif %}

    {{ form_row(form.image) }}

    {{ form_row(form.categories) }}

    {# Pour le bouton, pas de label ni d'erreur, on affiche juste le widget #}
    {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}

    {# Génération automatique des champs pas encore écrits.
       Dans cet exemple, ce serait le champ CSRF (géré automatiquement par Symfony !)
       et tous les champs cachés (type « hidden »). #}
    {{ form_rest(form) }}

    {# Fermeture de la balise <form> du formulaire HTML #}
    {{ form_end(form) }}
</div>

{# On charge la bibliothèque jQuery. Ici, je la prends depuis le CDN google
   mais si vous l'avez en local, changez simplement l'adresse. #}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

{# Voici le script en question : #}
<script type="text/javascript">
    $(document).ready(function() {
        // On récupère la balise <div> en question qui contient l'attribut « data-prototype » qui nous intéresse.
        var $container = $('div#advert_categories');

        // On définit un compteur unique pour nommer les champs qu'on va ajouter dynamiquement
        var index = $container.find(':input').length;

        // On ajoute un nouveau champ à chaque clic sur le lien d'ajout.
        $('#add_category').click(function(e) {
            addCategory($container);

            e.preventDefault(); // évite qu'un # apparaisse dans l'URL
            return false;
        });

        // On ajoute un premier champ automatiquement s'il n'en existe pas déjà un (cas d'une nouvelle annonce par exemple).
        if (index == 0) {
            addCategory($container);
        } else {
            // S'il existe déjà des catégories, on ajoute un lien de suppression pour chacune d'entre elles
            $container.children('div').each(function() {
                addDeleteLink($(this));
            });
        }

        // La fonction qui ajoute un formulaire CategoryType
        function addCategory($container) {
            // Dans le contenu de l'attribut « data-prototype », on remplace :
            // - le texte "__name__label__" qu'il contient par le label du champ
            // - le texte "__name__" qu'il contient par le numéro du champ
            var template = $container.attr('data-prototype')
                .replace(/__name__label__/g, 'Catégorie n°' + (index+1))
                .replace(/__name__/g,        index)
            ;

            // On crée un objet jquery qui contient ce template
            var $prototype = $(template);

            // On ajoute au prototype un lien pour pouvoir supprimer la catégorie
            addDeleteLink($prototype);

            // On ajoute le prototype modifié à la fin de la balise <div>
            $container.append($prototype);

            // Enfin, on incrémente le compteur pour que le prochain ajout se fasse avec un autre numéro
            index++;
        }

        // La fonction qui ajoute un lien de suppression d'une catégorie
        function addDeleteLink($prototype) {
            // Création du lien
            var $deleteLink = $('<a href="#" class="btn btn-danger">Supprimer</a>');

            // Ajout du lien
            $prototype.append($deleteLink);

            // Ajout du listener sur le clic du lien pour effectivement supprimer la catégorie
            $deleteLink.click(function(e) {
                $prototype.remove();

                e.preventDefault(); // évite qu'un # apparaisse dans l'URL
                return false;
            });
        }
    });
</script>

src/OC/PlatformBundle/Resources/views/Advert/index.html.twig
{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Accueil - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}
    <div>
        {% for message in app.session.flashbag.get('info') %}
            <p>Flash message: {{ message }}</p>
        {% endfor %}
    </div>
    <h2>List of adverts saved</h2>

    <ul>
        {% for advert in listAdverts %}
            <li>
                <a href="{{ path('oc_platform_view', {'id': advert.id}) }}">
                    {{ advert.title }}
                </a>
                par {{ advert.author }},
                le {{ advert.date|date('d/m/Y') }}
            </li>
        {% else %}
            <li>None advert saved.</li>
        {% endfor %}
    </ul>

    <ul class="pagination">
    {% for p in range(1, nbPages) %}
        <li {% if p == page  %} class="active" {% endif %}>
            <a href="{{ path('oc_platform_home', {'page': p }) }}">{{ p }}</a>
        </li>
    {% endfor %}
    </ul>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/menu.html.twig
{# Generate URL with the path Twig function, and provide a view with the id from the table given by the controller #}
<ul class="nav nav-pills nav-stacked">
    {% for advert in listAdverts %}
        <li>
            <a href="{{ path('oc_platform_view', {'id': advert.id}) }}">
                {{ advert.title }}
            </a>
        </li>
    {% endfor %}
</ul>

src/OC/PlatformBundle/Resources/views/Advert/view.html.twig
{# src/OC/PlatformBundle/Resources/view/Advert/view.html.twig #}

{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Consulting advert - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

    <div style="float: left; margin-right: 1em;">
        {# On vérifie qu'une image soit bien associée à l'article #}
        {% if advert.image is not null %}
            <img
                    src="{{ asset(advert.image.webPath) }}"
                    alt="{{ advert.image.alt }}"
                    height="60"
            />
        {% endif %}
    </div>

    <h2>{{ advert.title }}</h2>
    <i>Published by {{ advert.author }}, on {{ advert.date|date('d/m/Y') }}</i>

    <div class="well">
        {{ advert.content }}
    </div>

    {% if not advert.categories.empty %}
        <p>
            This advert has appeared in category :
            {% for category in advert.categories %}
                {{ category.name }}{% if not loop.last %}, {% endif %}
            {% endfor %}
        </p>
    {% endif %}

    {% if listAdvertSkills|length > 0 %}
        <div>
            Skills required for this advert are :
            <ul>
                {% for advertSkill in listAdvertSkills %}
                    <li>{{ advertSkill.skill.name }} : level {{ advertSkill.level }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <p>
        <a href="{{ path('oc_platform_home') }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Back to the list view
        </a>
        <a href="{{ path('oc_platform_edit', {'id': advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-edit"></i>
            Edit the advert
        </a>
        <a href="{{ path('oc_platform_delete', {'id': advert.id}) }}" class="btn btn-danger">
            <i class="glyphicon glyphicon-trash"></i>
            Delete this advert
        </a>
    </p>

{% endblock %}